apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 23.0.2
  name: icp4adeploy
spec:
  appVersion: 23.0.2
  datasource_configuration:
    dc_gcd_datasource:
      database_name: GCDDB
      database_port: "1433"
      database_servername: mssql.mssql.svc.cluster.local
      dc_common_gcd_datasource_name: FNGCDDS
      dc_common_gcd_xa_datasource_name: FNGCDDSXA
      dc_database_type: sqlserver
    dc_icn_datasource:
      database_name: ICNDB
      database_port: "1433"
      database_servername: mssql.mssql.svc.cluster.local
      dc_common_icn_datasource_name: ECMClientDS
      dc_database_type: sqlserver
    dc_os_datasources:
      - database_name: OS1DB
        database_port: "1433"
        database_servername: mssql.mssql.svc.cluster.local
        dc_common_os_datasource_name: FNOS1DS
        dc_common_os_xa_datasource_name: FNOS1DSXA
        dc_database_type: sqlserver
        dc_os_label: os1
      - database_name: OS2DB
        database_port: "1433"
        database_servername: mssql.mssql.svc.cluster.local
        dc_common_os_datasource_name: FNOS2DS
        dc_common_os_xa_datasource_name: FNOS2DSXA
        dc_database_type: sqlserver
        dc_os_label: os2
      - database_name: OS3DB
        database_port: "1433"
        database_servername: mssql.mssql.svc.cluster.local
        dc_common_os_datasource_name: FNOS3DS
        dc_common_os_xa_datasource_name: FNOS3DSXA
        dc_database_type: sqlserver
        dc_os_label: os3
      - database_name: OS4DB
        database_port: "1433"
        database_servername: mssql.mssql.svc.cluster.local
        dc_common_os_datasource_name: FNOS4DS
        dc_common_os_xa_datasource_name: FNOS4DSXA
        dc_database_type: sqlserver
        dc_os_label: os4
      - database_name: OS5DB
        database_port: "1433"
        database_servername: mssql.mssql.svc.cluster.local
        dc_common_os_datasource_name: FNOS5DS
        dc_common_os_xa_datasource_name: FNOS5DSXA
        dc_database_type: sqlserver
        dc_os_label: os5
      - database_name: CICDOS1DB
        database_port: "1433"
        database_servername: mssql.mssql.svc.cluster.local
        dc_common_os_datasource_name: FNCICDOS1DS
        dc_common_os_xa_datasource_name: FNCICDOS1DSXA
        dc_database_type: sqlserver
        dc_os_label: cicdos1
    dc_ssl_enabled: false
  ecm_configuration:
    cpe:
      arch:
        amd64: 3 - Most preferred
      auto_scaling:
        enabled: false
        max_replicas: "5"
        min_replicas: "3"
        target_cpu_utilization_percentage: "80"
      collectd_enable_plugin_write_graphite: false
      cpe_production_setting:
        gcd_jndi_name: FNGCDDS
        gcd_jndixa_name: FNGCDDSXA
        jvm_customize_options: null
        jvm_initial_heap_percentage: 18
        jvm_max_heap_percentage: 33
        license: accept
        license_model: FNCM.PVUNonProd
        time_zone: Etc/UTC
      datavolume:
        existing_pvc_for_cpe_bootstrapstore:
          name: cpe-bootstrapstore
          size: 1Gi
        existing_pvc_for_cpe_cfgstore:
          name: cpe-cfgstore
          size: 1Gi
        existing_pvc_for_cpe_filestore:
          name: cpe-filestore
          size: 1Gi
        existing_pvc_for_cpe_fnlogstore:
          name: cpe-fnlogstore
          size: 1Gi
        existing_pvc_for_cpe_icmrulestore:
          name: cpe-icmrulesstore
          size: 1Gi
        existing_pvc_for_cpe_logstore:
          name: cpe-logstore
          size: 1Gi
        existing_pvc_for_cpe_textextstore:
          name: cpe-textextstore
          size: 3Gi
      image:
        pull_policy: IfNotPresent
        repository: cp.icr.io/cp/cp4a/fncm/cpe
        tag: 23.0.2-IF003
      image_pull_secrets:
        name: ibm-entitlement-key
      log:
        format: json
      logging_enabled: false
      monitor_enabled: false
      probe:
        liveness:
          failure_threshold: 6
          period_seconds: 30
          timeout_seconds: 5
        readiness:
          failure_threshold: 6
          period_seconds: 30
          timeout_seconds: 10
        startup:
          failure_threshold: 16
          initial_delay_seconds: 120
          period_seconds: 30
          timeout_seconds: 10
      replica_count: 2
      resources:
        limits:
          cpu: 1
          ephemeral_storage: 4Gi
          memory: 3072Mi
        requests:
          cpu: 1
          ephemeral_storage: 4Gi
          memory: 3072Mi
      security_context:
        fs_groupchangepolicy: null
        selinux_options: null
        supplemental_groups: null
    fncm_secret_name: ibm-fncm-secret
    graphql:
      graphql_production_setting:
        enable_graph_iql: true
  ibm_license: accept
  initialize_configuration:
    ic_css_creation:
      - css_text_search_server_name: icp4adeploy-css-1
    ic_css_index_area:
      - index_area_name: os1_index_area
        object_store_name: OS1
      - index_area_name: os2_index_area
        object_store_name: OS2
      - index_area_name: os3_index_area
        object_store_name: OS3
      - index_area_name: os4_index_area
        object_store_name: OS4
      - index_area_name: os5_index_area
        object_store_name: OS5
      - index_area_name: cicdos1_index_area
        object_store_name: CICDOS1
    ic_domain_creation:
      domain_name: P8DOMAIN
      encryption_key: "128"
    ic_enable_cbr:
      - object_store_name: OS1
      - object_store_name: OS2
      - object_store_name: OS3
      - object_store_name: OS4
      - object_store_name: OS5
      - object_store_name: CICDOS1
    ic_icn_init_info:
      icn_desktop:
        - add_desktop_description: This is OS1 desktop
          add_desktop_id: OS1
          add_desktop_name: OS1
          add_desktop_repo_id: OS1
        - add_desktop_description: This is OS2 desktop
          add_desktop_id: OS2
          add_desktop_name: OS2
          add_desktop_repo_id: OS2
        - add_desktop_description: This is OS3 desktop
          add_desktop_id: OS3
          add_desktop_name: OS3
          add_desktop_repo_id: OS3
        - add_desktop_description: This is OS4 desktop
          add_desktop_id: OS4
          add_desktop_name: OS4
          add_desktop_repo_id: OS4
        - add_desktop_description: This is OS5 desktop
          add_desktop_id: OS5
          add_desktop_name: OS5
          add_desktop_repo_id: OS5
        - add_desktop_description: This is CICDOS1 desktop
          add_desktop_id: CICDOS1
          add_desktop_name: CICDOS1
          add_desktop_repo_id: CICDOS1
      icn_repos:
        - add_repo_id: OS1
          add_repo_os_dis_name: OS1
          add_repo_os_sym_name: OS1
        - add_repo_id: OS2
          add_repo_os_dis_name: OS2
          add_repo_os_sym_name: OS2
        - add_repo_id: OS3
          add_repo_os_dis_name: OS3
          add_repo_os_sym_name: OS3
        - add_repo_id: OS4
          add_repo_os_dis_name: OS4
          add_repo_os_sym_name: OS4
        - add_repo_id: OS5
          add_repo_os_dis_name: OS5
          add_repo_os_sym_name: OS5
        - add_repo_id: CICDOS1
          add_repo_os_dis_name: CICDOS1
          add_repo_os_sym_name: CICDOS1
    ic_ldap_creation:
      ic_ldap_admin_user_name:
        - cpadmin
      ic_ldap_admins_groups_name:
        - cpadmins
      ic_ldap_name: ldap
    ic_obj_store_creation:
      object_stores:
        - oc_cpe_obj_store_addons_list:
            - '{CE460ADD-0000-0000-0000-000000000004}'
            - '{CE460ADD-0000-0000-0000-000000000001}'
            - '{CE460ADD-0000-0000-0000-000000000003}'
            - '{CE511ADD-0000-0000-0000-000000000006}'
            - '{CE460ADD-0000-0000-0000-000000000008}'
            - '{CE460ADD-0000-0000-0000-000000000007}'
            - '{CE460ADD-0000-0000-0000-000000000009}'
            - '{CE460ADD-0000-0000-0000-00000000000A}'
            - '{CE460ADD-0000-0000-0000-00000000000B}'
            - '{CE460ADD-0000-0000-0000-00000000000D}'
            - '{CE511ADD-0000-0000-0000-00000000000F}'
            - '{CE511ADD-0000-0000-0000-000000000010}'
            - '{CE511ADD-0000-0000-0000-000000000015}'
            - '{CE521ADD-0000-0000-0000-000000000016}'
            - '{CE552ADD-0000-0000-0000-00000000001C}'
            - '{CE551ADD-0000-0000-0000-000000000011}'
            - '{CE554ADD-0000-0000-0000-000000000021}'
          oc_cpe_obj_store_admin_user_groups:
            - cpadmins
          oc_cpe_obj_store_conn:
            dc_os_datasource_name: FNOS1DS
            dc_os_xa_datasource_name: FNOS1DSXA
            name: OS1_dbconnection
          oc_cpe_obj_store_display_name: OS1
          oc_cpe_obj_store_enable_content_event_emitter: true
          oc_cpe_obj_store_symb_name: OS1
        - oc_cpe_obj_store_addons_list:
            - '{CE460ADD-0000-0000-0000-000000000004}'
            - '{CE460ADD-0000-0000-0000-000000000001}'
            - '{CE460ADD-0000-0000-0000-000000000003}'
            - '{CE511ADD-0000-0000-0000-000000000006}'
            - '{CE460ADD-0000-0000-0000-000000000008}'
            - '{CE460ADD-0000-0000-0000-000000000007}'
            - '{CE460ADD-0000-0000-0000-000000000009}'
            - '{CE460ADD-0000-0000-0000-00000000000A}'
            - '{CE460ADD-0000-0000-0000-00000000000B}'
            - '{CE460ADD-0000-0000-0000-00000000000D}'
            - '{CE511ADD-0000-0000-0000-00000000000F}'
            - '{CE511ADD-0000-0000-0000-000000000010}'
            - '{CE511ADD-0000-0000-0000-000000000015}'
            - '{CE521ADD-0000-0000-0000-000000000016}'
            - '{CE552ADD-0000-0000-0000-00000000001C}'
            - '{CE551ADD-0000-0000-0000-000000000011}'
            - '{CE554ADD-0000-0000-0000-000000000021}'
          oc_cpe_obj_store_admin_user_groups:
            - cpadmins
          oc_cpe_obj_store_conn:
            dc_os_datasource_name: FNOS2DS
            dc_os_xa_datasource_name: FNOS2DSXA
            name: OS2_dbconnection
          oc_cpe_obj_store_display_name: OS2
          oc_cpe_obj_store_enable_content_event_emitter: true
          oc_cpe_obj_store_symb_name: OS2
        - oc_cpe_obj_store_addons_list:
            - '{CE460ADD-0000-0000-0000-000000000004}'
            - '{CE460ADD-0000-0000-0000-000000000001}'
            - '{CE460ADD-0000-0000-0000-000000000003}'
            - '{CE511ADD-0000-0000-0000-000000000006}'
            - '{CE460ADD-0000-0000-0000-000000000008}'
            - '{CE460ADD-0000-0000-0000-000000000007}'
            - '{CE460ADD-0000-0000-0000-000000000009}'
            - '{CE460ADD-0000-0000-0000-00000000000A}'
            - '{CE460ADD-0000-0000-0000-00000000000B}'
            - '{CE460ADD-0000-0000-0000-00000000000D}'
            - '{CE511ADD-0000-0000-0000-00000000000F}'
            - '{CE511ADD-0000-0000-0000-000000000010}'
            - '{CE511ADD-0000-0000-0000-000000000015}'
            - '{CE521ADD-0000-0000-0000-000000000016}'
            - '{CE552ADD-0000-0000-0000-00000000001C}'
            - '{CE551ADD-0000-0000-0000-000000000011}'
            - '{CE554ADD-0000-0000-0000-000000000021}'
          oc_cpe_obj_store_admin_user_groups:
            - cpadmins
          oc_cpe_obj_store_conn:
            dc_os_datasource_name: FNOS3DS
            dc_os_xa_datasource_name: FNOS3DSXA
            name: OS3_dbconnection
          oc_cpe_obj_store_display_name: OS3
          oc_cpe_obj_store_enable_content_event_emitter: true
          oc_cpe_obj_store_symb_name: OS3
        - oc_cpe_obj_store_addons_list:
            - '{CE460ADD-0000-0000-0000-000000000004}'
            - '{CE460ADD-0000-0000-0000-000000000001}'
            - '{CE460ADD-0000-0000-0000-000000000003}'
            - '{CE511ADD-0000-0000-0000-000000000006}'
            - '{CE460ADD-0000-0000-0000-000000000008}'
            - '{CE460ADD-0000-0000-0000-000000000007}'
            - '{CE460ADD-0000-0000-0000-000000000009}'
            - '{CE460ADD-0000-0000-0000-00000000000A}'
            - '{CE460ADD-0000-0000-0000-00000000000B}'
            - '{CE460ADD-0000-0000-0000-00000000000D}'
            - '{CE511ADD-0000-0000-0000-00000000000F}'
            - '{CE511ADD-0000-0000-0000-000000000010}'
            - '{CE511ADD-0000-0000-0000-000000000015}'
            - '{CE521ADD-0000-0000-0000-000000000016}'
            - '{CE552ADD-0000-0000-0000-00000000001C}'
            - '{CE551ADD-0000-0000-0000-000000000011}'
            - '{CE554ADD-0000-0000-0000-000000000021}'
          oc_cpe_obj_store_admin_user_groups:
            - cpadmins
          oc_cpe_obj_store_conn:
            dc_os_datasource_name: FNOS4DS
            dc_os_xa_datasource_name: FNOS4DSXA
            name: OS4_dbconnection
          oc_cpe_obj_store_display_name: OS4
          oc_cpe_obj_store_enable_content_event_emitter: true
          oc_cpe_obj_store_symb_name: OS4
        - oc_cpe_obj_store_addons_list:
            - '{CE460ADD-0000-0000-0000-000000000004}'
            - '{CE460ADD-0000-0000-0000-000000000001}'
            - '{CE460ADD-0000-0000-0000-000000000003}'
            - '{CE511ADD-0000-0000-0000-000000000006}'
            - '{CE460ADD-0000-0000-0000-000000000008}'
            - '{CE460ADD-0000-0000-0000-000000000007}'
            - '{CE460ADD-0000-0000-0000-000000000009}'
            - '{CE460ADD-0000-0000-0000-00000000000A}'
            - '{CE460ADD-0000-0000-0000-00000000000B}'
            - '{CE460ADD-0000-0000-0000-00000000000D}'
            - '{CE511ADD-0000-0000-0000-00000000000F}'
            - '{CE511ADD-0000-0000-0000-000000000010}'
            - '{CE511ADD-0000-0000-0000-000000000015}'
            - '{CE521ADD-0000-0000-0000-000000000016}'
            - '{CE552ADD-0000-0000-0000-00000000001C}'
            - '{CE551ADD-0000-0000-0000-000000000011}'
            - '{CE554ADD-0000-0000-0000-000000000021}'
          oc_cpe_obj_store_admin_user_groups:
            - cpadmins
          oc_cpe_obj_store_conn:
            dc_os_datasource_name: FNOS5DS
            dc_os_xa_datasource_name: FNOS5DSXA
            name: OS5_dbconnection
          oc_cpe_obj_store_display_name: OS5
          oc_cpe_obj_store_enable_content_event_emitter: true
          oc_cpe_obj_store_symb_name: OS5
        - oc_cpe_obj_store_addons_list:
            - '{CE460ADD-0000-0000-0000-000000000004}'
            - '{CE460ADD-0000-0000-0000-000000000001}'
            - '{CE460ADD-0000-0000-0000-000000000003}'
            - '{CE511ADD-0000-0000-0000-000000000006}'
            - '{CE460ADD-0000-0000-0000-000000000008}'
            - '{CE460ADD-0000-0000-0000-000000000007}'
            - '{CE460ADD-0000-0000-0000-000000000009}'
            - '{CE460ADD-0000-0000-0000-00000000000A}'
            - '{CE460ADD-0000-0000-0000-00000000000B}'
            - '{CE460ADD-0000-0000-0000-00000000000D}'
            - '{CE511ADD-0000-0000-0000-00000000000F}'
            - '{CE511ADD-0000-0000-0000-000000000010}'
            - '{CE511ADD-0000-0000-0000-000000000015}'
            - '{CE521ADD-0000-0000-0000-000000000016}'
            - '{CE552ADD-0000-0000-0000-00000000001C}'
            - '{CE551ADD-0000-0000-0000-000000000011}'
            - '{CE554ADD-0000-0000-0000-000000000021}'
          oc_cpe_obj_store_admin_user_groups:
            - cpadmins
          oc_cpe_obj_store_conn:
            dc_os_datasource_name: FNCICDOS1DS
            dc_os_xa_datasource_name: FNCICDOS1DSXA
            name: CICDOS1_dbconnection
          oc_cpe_obj_store_display_name: CICDOS1
          oc_cpe_obj_store_enable_content_event_emitter: true
          oc_cpe_obj_store_symb_name: CICDOS1
  ldap_configuration:
    custom:
      lc_group_filter: (&(cn=%v)(|(objectclass=groupOfNames)(objectclass=groupofuniquenames)(objectclass=groupofurls)))
      lc_user_filter: (&(uid=%v)(objectclass=inetOrgPerson))
    lc_bind_secret: ldap-bind-secret
    lc_ldap_base_dn: dc=cp,dc=internal
    lc_ldap_group_base_dn: ou=Groups,dc=cp,dc=internal
    lc_ldap_group_display_name_attr: cn
    lc_ldap_group_member_id_map: groupOfNames:member
    lc_ldap_group_membership_search_filter: (|(&(objectclass=groupOfNames)(member={0}))(&(objectclass=groupofuniquenames)(uniquemember={0})))
    lc_ldap_group_name_attribute: '*:cn'
    lc_ldap_port: "389"
    lc_ldap_server: openldap.cp4ba-openldap.svc.cluster.local
    lc_ldap_ssl_enabled: false
    lc_ldap_user_display_name_attr: cn
    lc_ldap_user_name_attribute: '*:cn'
    lc_selected_ldap_type: Custom
  navigator_configuration:
    icn_production_setting:
      copy_files_to_war: navigator_war_filesources.xml
      icn_table_space: ICNDB
  shared_configuration:
    encryption_key_secret: ibm-iaws-shared-key-secret
    image_pull_secrets:
      - ibm-entitlement-key
    no_log: false
    sc_deployment_context: CP4A
    sc_deployment_fncm_license: production
    sc_deployment_license: production
    sc_deployment_patterns: foundation,content
    sc_deployment_platform: OCP
    sc_deployment_profile_size: small
    sc_deployment_type: Production
    sc_egress_configuration:
      sc_restricted_internet_access: false
    sc_iam:
      default_admin_username: cpfsadmin
    sc_image_repository: cp.icr.io
    sc_ingress_enable: false
    sc_optional_components: cmis,css
    show_sensitive_log: true
    storage_configuration:
      sc_block_storage_classname: managed-csi
      sc_fast_file_storage_classname: azurefile-csi
      sc_medium_file_storage_classname: azurefile-csi
      sc_slow_file_storage_classname: azurefile-csi
    trusted_certificate_list: []
  verify_configuration:
    vc_cpe_verification:
      vc_cpe_cbr:
        - cbr_cpe_obj_store_name: OS1
        - cbr_cpe_obj_store_name: OS2
        - cbr_cpe_obj_store_name: OS3
        - cbr_cpe_obj_store_name: OS4
        - cbr_cpe_obj_store_name: OS5
        - cbr_cpe_obj_store_name: CICDOS1
    vc_icn_verification:
      - vc_icn_desktop_id: OS1
        vc_icn_repository: OS1
      - vc_icn_desktop_id: OS2
        vc_icn_repository: OS2
      - vc_icn_desktop_id: OS3
        vc_icn_repository: OS3
      - vc_icn_desktop_id: OS4
        vc_icn_repository: OS4
      - vc_icn_desktop_id: OS5
        vc_icn_repository: OS5
      - vc_icn_desktop_id: CICDOS1
        vc_icn_repository: CICDOS1
